/* eslint-disable react/jsx-key */
import Head from "next/head";
import useWordle from "../utils/useWordle";
import Board from "../components/Board";
import KeyPad from "../components/KeyPad/";
import Nav from "../components/Nav";

export default function Home() {
  const [currentGuess, colorsForLetters, guesses, numOfGuesses, isNotAWord] =
    useWordle();
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <Nav />
        <Board
          currentGuess={currentGuess}
          colorsForLetters={colorsForLetters}
          guesses={guesses}
          numOfGuesses={numOfGuesses}
          isNotAWord={isNotAWord}
        />
        <KeyPad />
      </main>
    </div>
  );
}
