/* eslint-disable react/jsx-key */
import Head from "next/head";
import styles from "../styles/Home.module.css";
import useWordle from "../components/useWordle";
import WordleGrid from "../components/WordleGrid";
import KeyPad from "../components/KeyPad/";

export default function Home() {
  const [currentGuess, colorsForLetters, guesses, numOfGuesses, isNotAWord] =
    useWordle();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <WordleGrid
          currentGuess={currentGuess}
          colorsForLetters={colorsForLetters}
          guesses={guesses}
          numOfGuesses={numOfGuesses}
          isNotAWord={isNotAWord}
        />
        <KeyPad />
      </main>
    </div>
  );
}
